---
RuhohSpec: '0.1'

theme : twitter
permalink: /blog/:year/:month/:filename

production_url : http://lbrandy.com/blog

comments :
  provider : disqus
  disqus :
    short_name : lbrandy
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light

analytics :
  provider : google
  google : 
      tracking_id : 'UA-4513764-3'
  getclicky :
    site_id : 

syntax :
  provider : google_prettify
  google_prettify : 
      theme: sons-of-obsidian
      linenums : true